### ISSUE TITLE
Deprecations/deletions for version 3

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#217]
Deprecated things to delete and document in a migration guide for version 3:
 - [x] `DecoratorProcessor` for `layout:decorator`, replaced by `layout:decorate`, #95
 - [x] `$DECORATOR_TITLE` from the `layout:title-pattern` processor, replaced by `$LAYOUT_TITLE`, #95 
 - [x] `AppendingStrategy` for processing `<head>` sections, replaced by `AppendingRespectLayoutTitleStrategy` which will be renamed to take its place, #177 
 - [x] `GroupingStrategy` for processing `<head>` sections, replaced by `GroupingRespectLayoutTitleStrategy` which will be renamed to take its place, #177 

New deprecations for version 3:
 - [x] `CollectFragmentProcessor` for `layout:collect`, with no replacement, #166 

Deprecations that will remain for version 3:
 - `IncludeProcessor` for `layout:include`, was targeting a release of Thymeleaf 3.1+
